/**
 * COMPETITIVE ANALYSIS DATABASE SCHEMA v1
 */
export const fetchDummyCategory = () => ({
  success: true,
  message: "Dummy category fetch successful",
  categories: [
    { id: 1, categoryName: "electronics" },
    { id: 2, categoryName: "fashion" },
    { id: 3, categoryName: "home" },
    { id: 4, categoryName: "beauty" },
    { id: 5, categoryName: "sports" },
  ],
});

export const fetchCompetitorsDummy = () => ({
  success: true,
  message: "Dummy competitors fetch successful",
  competitors: [
    {
      id: 1,
      categoryName: "electronics",
      competitorName: "Apple",
      founded: "1976",
      headquarters: "Cupertino, USA",
      industry: "Technology",
      revenue: "$274B",
      officialWebsite: "https://www.apple.com",
    },
    {
      id: 2,
      categoryName: "electronics",
      competitorName: "Samsung",
      founded: "1938",
      headquarters: "Seoul, South Korea",
      industry: "Electronics",
      revenue: "$200B",
      officialWebsite: "https://www.samsung.com",
    },
    {
      id: 3,
      categoryName: "electronics",
      competitorName: "Google",
      founded: "1998",
      headquarters: "Mountain View, USA",
      industry: "Technology",
      revenue: "$182B",
      officialWebsite: "https://www.google.com",
    },
    {
      id: 4,
      categoryName: "electronics",
      competitorName: "Xiaomi",
      founded: "2010",
      headquarters: "Beijing, China",
      industry: "Consumer Electronics",
      revenue: "$37B",
      officialWebsite: "https://www.mi.com",
    },
    {
      id: 5,
      categoryName: "electronics",
      competitorName: "OnePlus",
      founded: "2013",
      headquarters: "Shenzhen, China",
      industry: "Consumer Electronics",
      revenue: "$1B",
      officialWebsite: "https://www.oneplus.com",
    },
  ],
});

export const fetchCompetitorProductsDummy = () => ({
  success: true,
  message: "Dummy products fetch successful",
  products: [
    {
      id: 1,
      competitorName: "Apple",
      isMyCompanyProduct: false,
      model: "iPhone 15 Plus",
      features: {
        chip: "A16 Bionic Chip",
        display: "Super Retina XDR Display",
        protection: "Ceramic Shield",
        battery: "Larger Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "Face ID",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Siri",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Very High",
        priceTrend: "Stable",
        demand: "Extreme",
        marketShare: "30%",
      },
      reviews: {
        user: "AppleFan123",
        comment: "Best iPhone yet",
        date: "2024-03-18",
      },
      details: {
        price: 1099,
        userRating: "4.8/5",
        numberOfReviews: 1200,
        specialFeatures:
          "Face ID, Ceramic Shield, Wireless Charging, Super Retina XDR Display",
        reviewSentiment: {
          positive: "70%",
          neutral: "20%",
          negative: "10%",
        },
        featureImportance: {
          price: 0.8,
          userRating: 0.9,
          specialFeatures: 0.85,
        },
      },
    },
    {
      id: 2,
      competitorName: "Samsung",
      isMyCompanyProduct: false,
      model: "Galaxy S23 Ultra",
      features: {
        chip: "Exynos 2200",
        display: "Dynamic AMOLED 2X",
        protection: "Gorilla Glass Victus",
        battery: "Large Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "Fingerprint Sensor",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Bixby",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "High",
        priceTrend: "Slightly Rising",
        demand: "High",
        marketShare: "25%",
      },
      reviews: {
        user: "SamsungGuru",
        comment: "Impressive performance and display",
        date: "2024-04-05",
      },
      details: {
        price: 999,
        userRating: "4.6/5",
        numberOfReviews: 950,
        specialFeatures:
          "Fingerprint Sensor, Gorilla Glass Victus, Wireless Charging, Dynamic AMOLED 2X, Bixby",
        reviewSentiment: {
          positive: "65%",
          neutral: "25%",
          negative: "10%",
        },
        featureImportance: {
          price: 0.8,
          userRating: 0.9,
          specialFeatures: 0.85,
        },
      },
    },
    {
      id: 3,
      competitorName: "Google",
      isMyCompanyProduct: false,
      model: "Pixel 8 Pro",
      features: {
        chip: "Tensor G3 Chip",
        display: "Smooth OLED Display",
        protection: "Gorilla Glass",
        battery: "Long-lasting Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "In-display Fingerprint",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: false,
        assistant: "Google Assistant",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Rising",
        priceTrend: "Stable",
        demand: "Moderate",
        marketShare: "15%",
      },
      reviews: {
        user: "PixelLover",
        comment: "Great camera and clean Android experience",
        date: "2024-02-28",
      },
      details: {
        price: 799,
        userRating: "4.5/5",
        numberOfReviews: 700,
        specialFeatures:
          "In-display Fingerprint, Smooth OLED Display, Google Assistant",
        reviewSentiment: {
          positive: "60%",
          neutral: "30%",
          negative: "10%",
        },
        featureImportance: {
          price: 0.75,
          userRating: 0.85,
          specialFeatures: 0.8,
        },
      },
    },
    {
      id: 4,
      competitorName: "Xiaomi",
      isMyCompanyProduct: false,
      model: "Redmi Note 12 Pro",
      features: {
        chip: "Snapdragon 732G",
        display: "AMOLED Display",
        protection: "Gorilla Glass 5",
        battery: "5000mAh Battery",
        waterResistance: false,
        wirelessCharging: false,
        security: "Fingerprint Sensor",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "MIUI Assistant",
        batteryLife: "12 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Moderate",
        priceTrend: "Falling",
        demand: "High",
        marketShare: "10%",
      },
      reviews: {
        user: "XiaomiFan",
        comment: "Great value for money",
        date: "2024-03-10",
      },
      details: {
        price: 349,
        userRating: "4.4/5",
        numberOfReviews: 800,
        specialFeatures:
          "AMOLED Display, Gorilla Glass 5, Fingerprint Sensor, 5000mAh Battery",
        reviewSentiment: {
          positive: "60%",
          neutral: "30%",
          negative: "10%",
        },
        featureImportance: {
          price: 0.7,
          userRating: 0.8,
          specialFeatures: 0.75,
        },
      },
    },
    {
      id: 5,
      competitorName: "OnePlus",
      isMyCompanyProduct: false,
      model: "OnePlus 11",
      features: {
        chip: "Snapdragon 8 Gen 2",
        display: "Fluid AMOLED Display",
        protection: "Gorilla Glass Victus",
        battery: "4500mAh Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "In-display Fingerprint",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "OnePlus Assistant",
        batteryLife: "11 hours",
        weight: "1.15 kg",
      },
      insights: {
        popularity: "High",
        priceTrend: "Stable",
        demand: "Moderate",
        marketShare: "8%",
      },
      reviews: {
        user: "OnePlusUser",
        comment: "Smooth performance and clean software",
        date: "2024-03-22",
      },
      details: {
        price: 699,
        userRating: "4.5/5",
        numberOfReviews: 900,
        specialFeatures:
          "Fluid AMOLED Display, In-display Fingerprint, Gorilla Glass Victus, Fast Charging",
        reviewSentiment: {
          positive: "67%",
          neutral: "25%",
          negative: "8%",
        },
        featureImportance: {
          price: 0.75,
          userRating: 0.85,
          specialFeatures: 0.8,
        },
      },
    },
    {
      id: 6,
      competitorName: "TechNova",
      isMyCompanyProduct: true,
      model: "Nova Pro X",
      features: {
        chip: "NovaChip Pro",
        display: "Quantum OLED",
        protection: "Titanium Shield",
        battery: "5000mAh Fast Charge Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "NovaSecure ID",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Nova Assistant Pro",
        batteryLife: "12 hours",
        weight: "1.1 kg",
      },
      insights: {
        popularity: "Very High",
        priceTrend: "Rising",
        demand: "High",
        marketShare: "40%",
      },
      reviews: {
        user: "TechNovaLover",
        comment: "Innovative design and performance",
        date: "2024-04-10",
      },
      details: {
        price: 799,
        userRating: "4.7/5",
        numberOfReviews: 1100,
        specialFeatures: "Quantum OLED, Titanium Shield, Fast Charging",
        reviewSentiment: {
          positive: "72%",
          neutral: "20%",
          negative: "8%",
        },
        featureImportance: {
          price: 0.85,
          userRating: 0.9,
          specialFeatures: 0.88,
        },
      },
    },
    {
      id: 7,
      competitorName: "TechNova",
      isMyCompanyProduct: true,
      model: "Nova Edge",
      features: {
        chip: "NovaChip Edge",
        display: "Infinity AMOLED",
        protection: "Reinforced Glass",
        battery: "4800mAh Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "Edge Secure ID",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Nova Edge Assistant",
        batteryLife: "11 hours",
        weight: "1.05 kg",
      },
      insights: {
        popularity: "High",
        priceTrend: "Stable",
        demand: "Moderate",
        marketShare: "35%",
      },
      reviews: {
        user: "EdgeFan",
        comment: "Sleek design and reliable performance",
        date: "2024-04-08",
      },
      details: {
        price: 699,
        userRating: "4.6/5",
        numberOfReviews: 950,
        specialFeatures:
          "Infinity AMOLED, Reinforced Glass, Fast Wireless Charging",
        reviewSentiment: {
          positive: "70%",
          neutral: "25%",
          negative: "5%",
        },
        featureImportance: {
          price: 0.8,
          userRating: 0.85,
          specialFeatures: 0.82,
        },
      },
    },
    {
      id: 8,
      competitorName: "TechNova",
      isMyCompanyProduct: true,
      model: "Nova Max",
      features: {
        chip: "NovaChip Max",
        display: "UltraCrystal Display",
        protection: "Carbon Fiber Shield",
        battery: "5500mAh Ultra Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "Max Secure ID",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Nova Max Voice",
        batteryLife: "13 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Moderate",
        priceTrend: "Falling",
        demand: "High",
        marketShare: "38%",
      },
      reviews: {
        user: "MaxUser",
        comment: "Outstanding battery life and display quality",
        date: "2024-04-09",
      },
      details: {
        price: 899,
        userRating: "4.8/5",
        numberOfReviews: 1200,
        specialFeatures:
          "UltraCrystal Display, Carbon Fiber Shield, Ultra Battery",
        reviewSentiment: {
          positive: "75%",
          neutral: "20%",
          negative: "5%",
        },
        featureImportance: {
          price: 0.9,
          userRating: 0.92,
          specialFeatures: 0.88,
        },
      },
    },
  ],
});

/**
 * COMPETITIVE ANALYSIS DATABASE SCHEMA v1
 */
