/**
 * COMPETITIVE ANALYSIS DATABASE SCHEMA v1
 */
export const fetchDummyCategory = () => ({
  success: true,
  message: "Dummy category fetch successful",
  categories: [
    { id: 1, categoryName: "electronics" },
    { id: 2, categoryName: "fashion" },
    { id: 3, categoryName: "home" },
    { id: 4, categoryName: "beauty" },
    { id: 5, categoryName: "sports" },
  ],
});

export const fetchCompetitorsDummy = () => ({
  success: true,
  message: "Dummy competitors fetch successful",
  competitors: [
    {
      id: 1,
      categoryName: "electronics",
      competitorName: "Apple",
      founded: "1976",
      headquarters: "Cupertino, USA",
      industry: "Technology",
      revenue: "$274B",
      officialWebsite: "https://www.apple.com",
    },
    {
      id: 2,
      categoryName: "electronics",
      competitorName: "Samsung",
      founded: "1938",
      headquarters: "Seoul, South Korea",
      industry: "Electronics",
      revenue: "$200B",
      officialWebsite: "https://www.samsung.com",
    },
    {
      id: 3,
      categoryName: "electronics",
      competitorName: "Google",
      founded: "1998",
      headquarters: "Mountain View, USA",
      industry: "Technology",
      revenue: "$182B",
      officialWebsite: "https://www.google.com",
    },
    {
      id: 4,
      categoryName: "electronics",
      competitorName: "Xiaomi",
      founded: "2010",
      headquarters: "Beijing, China",
      industry: "Consumer Electronics",
      revenue: "$37B",
      officialWebsite: "https://www.mi.com",
    },
    {
      id: 5,
      categoryName: "electronics",
      competitorName: "OnePlus",
      founded: "2013",
      headquarters: "Shenzhen, China",
      industry: "Consumer Electronics",
      revenue: "$1B",
      officialWebsite: "https://www.oneplus.com",
    },
  ],
});

export const fetchCompetitorProductsDummy = () => ({
  success: true,
  message: "Dummy products fetch successful",
  products: [
    {
      id: 1,
      competitorName: "Apple",
      isMyCompanyProduct: false,
      features: {
        chip: "A16 Bionic Chip",
        display: "Super Retina XDR Display",
        protection: "Ceramic Shield",
        battery: "Larger Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "Face ID",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Siri",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Very High",
        priceTrend: "Stable",
        demand: "Extreme",
        marketShare: "30%",
      },
      model: "iPhone 15 Plus",
      reviews: {
        user: "AppleFan123",
        comment: "Best iPhone yet",
        date: "2024-03-18",
      },
    },
    {
      id: 2,
      competitorName: "Samsung",
      isMyCompanyProduct: false,
      features: {
        chip: "Exynos 2200",
        display: "Dynamic AMOLED 2X",
        protection: "Gorilla Glass Victus",
        battery: "Large Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "Fingerprint Sensor",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "Bixby",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "High",
        priceTrend: "Slightly Rising",
        demand: "High",
        marketShare: "25%",
      },
      model: "Galaxy S23 Ultra",
      reviews: {
        user: "SamsungGuru",
        comment: "Impressive performance and display",
        date: "2024-04-05",
      },
    },
    {
      id: 3,
      competitorName: "Google",
      isMyCompanyProduct: false,
      features: {
        chip: "Tensor G3 Chip",
        display: "Smooth OLED Display",
        protection: "Gorilla Glass",
        battery: "Long-lasting Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "In-display Fingerprint",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: false,
        assistant: "Google Assistant",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Rising",
        priceTrend: "Stable",
        demand: "Moderate",
        marketShare: "15%",
      },
      model: "Pixel 8 Pro",
      reviews: {
        user: "PixelLover",
        comment: "Great camera and clean Android experience",
        date: "2024-02-28",
      },
    },
    {
      id: 4,
      competitorName: "Xiaomi",
      isMyCompanyProduct: false,
      features: {
        chip: "Snapdragon 732G",
        display: "AMOLED Display",
        protection: "Gorilla Glass 5",
        battery: "5000mAh Battery",
        waterResistance: false,
        wirelessCharging: false,
        security: "Fingerprint Sensor",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "MIUI Assistant",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "Moderate",
        priceTrend: "Falling",
        demand: "High",
        marketShare: "10%",
      },
      model: "Redmi Note 12 Pro",
      reviews: {
        user: "XiaomiFan",
        comment: "Great value for money",
        date: "2024-03-10",
      },
    },
    {
      id: 5,
      competitorName: "OnePlus",
      isMyCompanyProduct: false,
      features: {
        chip: "Snapdragon 8 Gen 2",
        display: "Fluid AMOLED Display",
        protection: "Gorilla Glass Victus",
        battery: "4500mAh Battery",
        waterResistance: true,
        wirelessCharging: true,
        security: "In-display Fingerprint",
        bluetooth: true,
        wifi: true,
        gps: true,
        nfc: true,
        dualSim: true,
        assistant: "OnePlus Assistant",
        batteryLife: "10 hours",
        weight: "1.2 kg",
      },
      insights: {
        popularity: "High",
        priceTrend: "Stable",
        demand: "Moderate",
        marketShare: "8%",
      },
      model: "OnePlus 11",
      reviews: {
        user: "OnePlusUser",
        comment: "Smooth performance and clean software",
        date: "2024-03-22",
      },
    },
  ],
});

export const fetchSelectedCompetitorProductsDetailsDummy = () => ({
  success: true,
  message: "Dummy submission successful",
  details: [
    {
      id: 1,
      model: "iPhone 15 Plus",
      name: "Apple iPhone 15 Plus",
      price: 1099,
      userRating: "4.8/5",
      numberOfReviews: 1200,
      specialFeatures:
        "Face ID, Ceramic Shield, Wireless Charging, Super Retina XDR Display",
      reviewSentiment: {
        positive: "70%",
        neutral: "20%",
        negative: "10%",
      },
      featureImportance: {
        price: 0.8,
        userRating: 0.9,
        specialFeatures: 0.85,
      },
    },
    {
      id: 2,
      model: "Galaxy S23 Ultra",
      name: "Samsung Galaxy S23 Ultra",
      price: 999,
      userRating: "4.6/5",
      numberOfReviews: 950,
      specialFeatures:
        "Fingerprint Sensor, Gorilla Glass Victus, Wireless Charging, Dynamic AMOLED 2X, Bixby",
      reviewSentiment: {
        positive: "65%",
        neutral: "25%",
        negative: "10%",
      },
      featureImportance: {
        price: 0.8,
        userRating: 0.9,
        specialFeatures: 0.85,
      },
    },
    {
      id: 3,
      model: "Pixel 8 Pro",
      name: "Google Pixel 8 Pro",
      price: 899,
      userRating: "4.5/5",
      numberOfReviews: 1200,
      specialFeatures:
        "In-display Fingerprint, Gorilla Glass, Wireless Charging, Smooth OLED Display, Google Assistant",
      reviewSentiment: {
        positive: "70%",
        neutral: "20%",
        negative: "10%",
      },
      featureImportance: {
        price: 0.8,
        userRating: 0.9,
        specialFeatures: 0.85,
      },
    },
    {
      id: 4,
      model: "Redmi Note 12 Pro",
      name: "Xiaomi Redmi Note 12 Pro",
      price: 299,
      userRating: "4.2/5",
      numberOfReviews: 1100,
      specialFeatures:
        "Fingerprint Sensor, AMOLED Display, Large Battery, Gorilla Glass 5, MIUI Assistant",
      reviewSentiment: {
        positive: "65%",
        neutral: "25%",
        negative: "10%",
      },
      featureImportance: {
        price: 0.8,
        userRating: 0.9,
        specialFeatures: 0.85,
      },
    },
    {
      id: 5,
      model: "OnePlus 11",
      name: "OnePlus 11",
      price: 699,
      userRating: "4.4/5",
      numberOfReviews: 1300,
      specialFeatures:
        "In-display Fingerprint, Gorilla Glass Victus, Wireless Charging, Fluid AMOLED Display, OnePlus Assistant",
      reviewSentiment: {
        positive: "70%",
        neutral: "20%",
        negative: "10%",
      },
      featureImportance: {
        price: 0.8,
        userRating: 0.9,
        specialFeatures: 0.85,
      },
    },
  ],
});
/**
 * COMPETITIVE ANALYSIS DATABASE SCHEMA v1
 */
